---
- name: Deploy app container
  hosts: all
  environment:
    PYTHONPATH: /home/ubuntu/.local/lib/python3.5/site-packages:/usr/local/lib/python3.5/dist-packages
    LC_ALL: C
  tasks:

  - name: Run app container
    become: true
    docker_container:
      name: reddit-app
      image: rust118/otus-reddit:1.0
      ports: [ "9292:9292" ]
