---
- name: Install docker
  become: true
  hosts: all
  tasks:

  - name: Install deb packages required for docker
    apt:
      pkg: [ apt-transport-https, ca-certificates, gnupg-agent, software-properties-common ]
      update_cache: yes

  - name: Install gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Install docker repo
    apt_repository:
      filename: docker
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker-ce packages
    apt:
      pkg: [ docker-ce, docker-ce-cli, containerd.io ]
      update_cache: yes
