version: '3.3'

services:
  post_db:
    env_file: .env
    image: mongo:3.2
    volumes:
    - post_db:/data/db
    networks:
    - back_net

  post:
    env_file: .env
    build: ./post-py
    image: ${MY_USERNAME}/post:${MY_POST_VER}
    networks:
    - back_net
    - front_net

  comment:
    env_file: .env
    build: ./comment
    image: ${MY_USERNAME}/comment:${MY_COMMENT_VER}
    networks:
    - back_net
    - front_net

  ui:
    env_file: .env
    build: ./ui
    image: ${MY_USERNAME}/ui:${MY_UI_VER}
    ports:
    - ${MY_UI_PORT}:9292/tcp
    networks:
    - front_net
    - reddit

networks:
  reddit:
  front_net:
  back_net:


volumes:
  post_db:
